apiVersion: v1
data:
  cloud: QVpVUkVfU1RPUkFHRV9BQ0NPVU5UX0FDQ0VTU19LRVk9ImNZRzZXcDNTQmVWL2t3ZGVpMU5BRTNoK3A3T25XcUJ5UXQyM0ZMb2cxNVBNNDdVZlVjQTFBZlovY1IvUFdYSy9kbS80Y0ZuODd4b29ZWDMzTzZZdW1RPT0iCkFaVVJFX0NMT1VEX05BTUU9QXp1cmVQdWJsaWNDbG91ZApBWlVSRV9TVUJTQ1JJUFRJT05fSUQ9ODIzZTkzMGQtOGFjMS00NTBkLTgyNjctM2Y2ZThiOWY4ZmZkCnN0b3JhZ2VBY2NvdW50PXN0cmF0b3N2ZWxlcm8=
kind: Secret
metadata:
  labels:
    component: velero
  name: cloud-credentials
  namespace: velero
type: Opaque
