apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  # Name of the object store plugin to use to connect to this location.
  #
  # Required.
  provider: velero.io/azure

  objectStorage:
    # The bucket/blob container in which to store backups.
    #
    # Required.
    bucket: backups

    # The prefix within the bucket under which to store backups.
    #
    # Optional.
    prefix: stratos

  config:
    # Name of the resource group containing the storage account for this backup storage location.
    #
    # Required.
    resourceGroup: AMOL-SEDP-SBX-RG

    # Name of the storage account for this backup storage location.
    #
    # Required.
    storageAccount: stratosvelero

    # Name of the environment variable in $AZURE_CREDENTIALS_FILE that contains storage account key for this backup storage location.
    #
    # Required if using a storage account access key to authenticate rather than a service principal.
    # storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY

    # ID of the subscription for this backup storage location.
    #
    # Optional.
    subscriptionId: 823e930d-8ac1-450d-8267-3f6e8b9f8ffd

    # The block size, in bytes, to use when uploading objects to Azure blob storage.
    # See https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs
    # for more information on block blobs.
    #
    # Optional (defaults to 104857600, i.e. 100MB).
    #blockSizeInBytes: "104857600"