apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 50
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    updateStrategy: RollingUpdate
    image:
      repository: velero/velero
      tag: v1.5.3
    initContainers:
    - name: velero-plugin-for-microsoft-azure
      image: velero/velero-plugin-for-microsoft-azure:v1.1.1
      volumeMounts:
      - name: plugins
        mountPath: /target
      - name: cloud-credentials
        mountPath: /credentials
      - name: scratch
        mountPath: /scratch