apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      version: "2.14.4"
  test:
    enable: false
  values:
    updateStrategy: RollingUpdate
    image:
      repository: velero/velero
      tag: v1.5.3
    initContainers:
    - name: velero-plugin-for-microsoft-azure
      image: velero/velero-plugin-for-microsoft-azure:v1.1.1
      volumeMounts:
      - name: plugins
        mountPath: /target
      - name: cloud-credentials
        mountPath: /credentials
      - name: scratch
        mountPath: /scratch
    configuration:
      provider: azure
      backupStorageLocation:
        name: default
        bucket: backups
        config:
          resourceGroup: "AMOL-SEDP-SBX-RG"
          storageAccount: "stratosvelero"
          subscriptionId: "823e930d-8ac1-450d-8267-3f6e8b9f8ffd"
          storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      volumeSnapshotLocation:
        name: default
        config:
          resourceGroup: "AMOL-SEDP-SBX-RG"
          subscriptionId: "823e930d-8ac1-450d-8267-3f6e8b9f8ffd"
        apitimeout: 300s
    credentials:
      useSecret: true
      existingSecret: "cloud-credentials"
    envFrom:
      - name: "cloud-credentials"
    env:
      - name: VELERO_SCRATCH_DIR
        value: /scratch
      - name: VELERO_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: LD_LIBRARY_PATH
        value: /plugins
      - name: AZURE_CREDENTIALS_FILE
        value: /credentials/cloud
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi